version: "3"
services:
  app:
    build: .
    volumes:
    - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
  celery-worker:
    image: django-docker-lab
    valumes:
      - .:/django
      command: "celery -A django.tasks worker --loglevel=info"
  redis:
      image: redis:5.0-alpine
